apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitopscluster
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: all-openshift-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    gitOpsOperatorImage: "quay.io/argoprojlabs/argocd-operator@sha256:223ad82fb697471ede79201c4a042115c9ca5c00a172d5bdcd5a780e58c46c79"
    gitOpsImage: "quay.io/argoproj/argocd@sha256:bbdb994007855fed9adfbef31cd58c49f867e652c0e16654bf6579ff037e13e2"
    redisImage: "redis@sha256:8061ca607db2a0c80010aeb5fc9bed0253448bc68711eaa14253a392f6c48280"
    argoCDAgent:
      enabled: true
      propagateHubCA: true
      serverAddress: ""
      serverPort: ""
      mode: "managed"
      image: "ghcr.io/argoproj-labs/argocd-agent/argocd-agent:latest"
