//go:build !ignore_autogenerated

// Copyright 2022 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDAgentSpec) DeepCopyInto(out *ArgoCDAgentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.PropagateHubCA != nil {
		in, out := &in.PropagateHubCA, &out.PropagateHubCA
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDAgentSpec.
func (in *ArgoCDAgentSpec) DeepCopy() *ArgoCDAgentSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDAgentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoServerSpec) DeepCopyInto(out *ArgoServerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoServerSpec.
func (in *ArgoServerSpec) DeepCopy() *ArgoServerSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsAddonSpec) DeepCopyInto(out *GitOpsAddonSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ArgoCDAgent != nil {
		in, out := &in.ArgoCDAgent, &out.ArgoCDAgent
		*out = new(ArgoCDAgentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OverrideExistingConfigs != nil {
		in, out := &in.OverrideExistingConfigs, &out.OverrideExistingConfigs
		*out = new(bool)
		**out = **in
	}
	if in.OLMSubscription != nil {
		in, out := &in.OLMSubscription, &out.OLMSubscription
		*out = new(OLMSubscriptionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsAddonSpec.
func (in *GitOpsAddonSpec) DeepCopy() *GitOpsAddonSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsAddonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsCluster) DeepCopyInto(out *GitOpsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsCluster.
func (in *GitOpsCluster) DeepCopy() *GitOpsCluster {
	if in == nil {
		return nil
	}
	out := new(GitOpsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsClusterList) DeepCopyInto(out *GitOpsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitOpsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsClusterList.
func (in *GitOpsClusterList) DeepCopy() *GitOpsClusterList {
	if in == nil {
		return nil
	}
	out := new(GitOpsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsClusterSpec) DeepCopyInto(out *GitOpsClusterSpec) {
	*out = *in
	out.ArgoServer = in.ArgoServer
	if in.PlacementRef != nil {
		in, out := &in.PlacementRef, &out.PlacementRef
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.GitOpsAddon != nil {
		in, out := &in.GitOpsAddon, &out.GitOpsAddon
		*out = new(GitOpsAddonSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.CreateBlankClusterSecrets != nil {
		in, out := &in.CreateBlankClusterSecrets, &out.CreateBlankClusterSecrets
		*out = new(bool)
		**out = **in
	}
	if in.CreatePolicyTemplate != nil {
		in, out := &in.CreatePolicyTemplate, &out.CreatePolicyTemplate
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsClusterSpec.
func (in *GitOpsClusterSpec) DeepCopy() *GitOpsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsClusterStatus) DeepCopyInto(out *GitOpsClusterStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsClusterStatus.
func (in *GitOpsClusterStatus) DeepCopy() *GitOpsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OLMSubscriptionSpec) DeepCopyInto(out *OLMSubscriptionSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OLMSubscriptionSpec.
func (in *OLMSubscriptionSpec) DeepCopy() *OLMSubscriptionSpec {
	if in == nil {
		return nil
	}
	out := new(OLMSubscriptionSpec)
	in.DeepCopyInto(out)
	return out
}
