org: open-cluster-management

nameOverride: maestro-argocd-pullmodel
fullnameOverride: maestro-argocd-pullmodel

global: 
  pullPolicy: IfNotPresent
  imageOverrides:
    multicloud_integrations: quay.io/stolostron/multicloud-integrations:latest
    pullSecret: multiclusterhub-operator-pull-secret
hubconfig:
  proxyConfigs:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    NO_PROXY: ""
  ocpVersion: 4.12.0
  nodeSelector: null
  tolerations: []