apiVersion: apps.open-cluster-management.io/v1beta1
kind: GitOpsCluster
metadata:
  name: gitops-production
  namespace: openshift-gitops
spec:
  argoServer:
    argoNamespace: openshift-gitops
  placementRef:
    kind: Placement
    apiVersion: cluster.open-cluster-management.io/v1beta1
    name: production-clusters
    namespace: openshift-gitops
  gitopsAddon:
    enabled: true
    overrideExistingConfigs: true
    # GitOpsOperatorImage is the only image that needs to be specified.
    # All other images (ArgoCD, Redis, etc.) are handled by the operator.
    gitOpsOperatorImage: "registry.redhat.io/openshift-gitops-1/gitops-operator@sha256:..."
    argoCDAgent:
      enabled: true
      serverAddress: ""
      serverPort: ""
      mode: managed
      propagateHubCA: true
      # Note: Agent image uses the default Red Hat image from ARGOCD_PRINCIPAL_IMAGE.
      # To customize, modify the ArgoCD CR directly on the managed cluster.
