apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-agent-params
  namespace: {{ .Release.Namespace }}
data:
  agent.keep-alive-ping-interval: "50s"
  agent.mode: "{{ .Values.global.argocdAgent.mode }}"
  agent.creds: "mtls:CN=system:open-cluster-management:cluster:([^:]+):addon:gitops-addon:agent:gitops-addon-agent"
  agent.tls.client.insecure: "false"
  agent.log.level: "info"
  agent.namespace: "openshift-gitops"
  agent.redis.address: "acm-openshift-gitops-redis:6379"
  agent.server.address: "{{ .Values.global.argocdAgent.serverAddress }}"
  agent.server.port: "{{ .Values.global.argocdAgent.serverPort }}"
  agent.metrics.port: "8181"
  agent.healthz.port: "8002"
  agent.tls.root-ca-secret-name: "argocd-agent-ca"
  agent.tls.secret-name: "gitops-addon-open-cluster-management.io-argocd-agent-addon-client-cert"
